version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 8.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
wherearemytms = true
farmersdelight = true
reinfbarrel = true
seasonsextras = true
botania = true
enchanted-vertical-slabs = true
create = true
interiors = true
botaniacombat = true
minecraft = true
visualoverhaul = true
createutilities = true
lootr = true
createdeco = true
ae2 = true
create_enchantment_industry = true
farmersdelightexpansion = true
travelersbackpack = true
createaddition = true
railways = true
waystones = true
milk = true
sliceanddice = true
apcrcompat = true
decorative_blocks = true
handcrafted = true
universal_graves = true
cobblemon = true
reinfchest = true
creategoggles = true
